topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 1
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 9100
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 11500

jobs:
  fedora-rawhide/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-frawhide
          name: freeipa/ci-master-frawhide
          version: 0.0.4
        timeout: 1800
        topology: *build

  fedora-rawhide/test_server_del:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_server_del.py
        template: *ci-master-frawhide
        timeout: 8000
        topology: *master_2repl_1client

  fedora-rawhide/test_installation:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_installation.py
        template: *ci-master-frawhide
        timeout: 18000
        topology: *master_3repl_1client

  fedora-rawhide/TestServerInstall:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestServerInstall
        template: *ci-master-frawhide
        timeout: 12000
        topology: *master_1repl

  fedora-rawhide/TestReplicaInstall:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestReplicaInstall
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestClientInstall:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestClientInstall
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestIPACommands:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestIPACommands
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestCertInstall:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestCertInstall
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestPKINIT:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestPKINIT
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestServerReplicaCALessToCAFull:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_caless.py::TestServerReplicaCALessToCAFull
        template: *ci-master-frawhide
        timeout: 5400
        topology: *master_1repl

  fedora-rawhide/TestBackupAndRestore:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestore
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/TestBackupAndRestoreWithDNS:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithDNS
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/TestBackupReinstallRestoreWithDNS:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithDNS
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/TestBackupAndRestoreWithKRA:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithKRA
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/TestBackupReinstallRestoreWithKRA:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithKRA
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/test_dnssec:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_dnssec.py
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_2repl_1client

  fedora-rawhide/test_replica_promotion:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_replica_promotion.py
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/test_upgrade:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_upgrade.py
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_1repl

  fedora-rawhide/test_topology:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_topology.py
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_3repl_1client

  fedora-rawhide/test_replication_layouts.py:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_integration/test_replication_layouts.py
        template: *ci-master-frawhide
        timeout: 7200
        topology: *master_3repl_1client

  fedora-rawhide/test_webui:
    requires: [fedora-rawhide/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-rawhide/build_url}'
        test_suite: test_webui/
        template: *ci-master-frawhide
        timeout: 8000
        topology: *ipaserver
