language: python
services:
    - docker

cache: pip
env:
    global:
        - TEST_RUNNER_IMAGE="martbab/freeipa-fedora-test-runner:master-latest"
          TEST_RUNNER_CONFIG=".test_runner_config.yaml"
          PEP8_ERROR_LOG="pep8_errors.log"
          CI_RESULTS_LOG="ci_results_${TRAVIS_BRANCH}.log"
    matrix:
        - TASK_TO_RUN="lint"
        - TASK_TO_RUN="run-tests"
          TESTS_TO_RUN="test_xmlrpc/test_[a-k]*.py"
        - TASK_TO_RUN="run-tests"
          TESTS_TO_RUN="test_cmdline
            test_install
            test_ipalib
            test_ipapython
            test_ipaserver
            test_pkcs10
            test_xmlrpc/test_[l-z]*.py"
install:
    - pip install pep8
    - >
      pip3 install
      git+https://github.com/freeipa/ipa-docker-test-runner@release-0-2-1

script:
    - travis_wait 50 ./.travis_run_task.sh
after_failure:
    - echo "Test runner output:"; tail -n 5000 $CI_RESULTS_LOG
    - echo "PEP-8 errors:"; cat $PEP8_ERROR_LOG
