language: python
services:
    - docker

env:
    global:
        - TEST_RUNNER_IMAGE="martbab/freeipa-fedora-test-runner:master-latest"
    matrix:
        - TESTS_TO_RUN="test_xmlrpc/test_[a-k]*.py"
        - >
            TESTS_TO_RUN="test_cmdline
            test_install
            test_ipalib
            test_ipapython
            test_ipaserver
            test_pkcs10
            test_xmlrpc/test_[l-z]*.py"
before_install:
    - pip install pep8
    - >
      pip3 install
      git+https://github.com/freeipa/ipa-docker-test-runner@release-0-2-1

script:
    - ./.travis_run_task.sh
after_failure:
  - echo "Test runner output:"; tail -n 5000 ci_results_${TRAVIS_BRANCH}.log
  - echo "PEP-8 errors:"; cat pep8_errors.log
