topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-ipa-4-6-f27
          version: 1.0.1
        timeout: 1800
        topology: *build

  fedora-27/test_installation:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py
        template: *ci-master-f27
        timeout: 10800
        topology: *master_3repl_1client
