#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#
topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  pki-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &pki-master-latest
          name: freeipa/pki-master-f31
          version: 0.0.2
        timeout: 1800
        topology: *build

  pki-fedora/simple_replication:
    requires: [pki-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{pki-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_simple_replication.py
        template: *pki-master-latest
        timeout: 3600
        topology: *master_1repl

  pki-fedora/test_external_ca_TestExternalCA:
    requires: [pki-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{pki-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_external_ca.py::TestExternalCA
        template: *pki-master-latest
        timeout: 4800
        topology: *master_1repl_1client
